require("dotenv").config();
module.exports={
    PORT:process.env.PORT,
    MONGO_URL:process.env.MONGO_URL,
    JWT_SECRET:process.env.JWT_SECRET,
    JWT_SECRET_SELLER:process.env.JWT_SECRET_SELLER,
    NODE_ENV:process.env.NODE_ENV,
    SELLER_EMAIL:process.env.SELLER_EMAIL,
    SELLER_PASSWORD:process.env.SELLER_PASSWORD,


CLOUDINARY_CLOUD_NAME:process.env.CLOUDINARY_CLOUD_NAME,
CLOUDINARY_API_KEY:process.env.CLOUDINARY_API_KEY,
CLOUDINARY_API_SECRET:process.env.CLOUDINARY_API_SECRET,

STRIPE_PUBLISHABLE_KEY:process.env.STRIPE_PUBLISHABLE_KEY,
STRIPE_SECRET_KEY:process.env.STRIPE_SECRET_KEY,
STRIPE_WEBHOOK_SECRET:process.env.STRIPE_WEBHOOK_SECRET,

}